[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "serverwatcher"
version = "0.0.0"
description = "A HungerLib-powered Minecraft server automation engine."
readme = "README.md"
requires-python = ">=3.14"
license = { text = "GPL-3.0" }

authors = [
    { name = "iFamished" }
]

keywords = [
    "pterodactyl",
    "minecraft",
    "automation",
    "server-management",
    "hungerlib",
    "hungernet"
]

dependencies = [
    "hungerlib>=3.1",
    "mapres",
    "C2E",
]

classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries",
    "Topic :: System :: Systems Administration",
]

[project.urls]
Homepage = "https://github.com/iFamished/ServerWatcher"
Documentation = "https://github.com/iFamished/ServerWatcher"
Source = "https://github.com/iFamished/ServerWatcher"
Issues = "https://github.com/iFamished/ServerWatcher/issues"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
serverwatcher = ["defaultconfigs/*.yaml"]