timezone: 'America/Chicago'

panel:
  name: 'My Panel'
  url: 'https://example.com'
  api_key: 'CHANGE_ME'

origin:
  server_id: 'CHANGE_ME'

server:
  name: 'My SMP'
  server_id: 'CHANGE_ME'
  domain: 'mc.example.com'
  port: 25565
  tps_command: 'ticks'

hungerbridge:
  token: 'CHANGE_ME'
  port: 1913

logger:
  enabled: True
  name: 'Server Watcher'
  log_path: '/home/container/logs/'
  
  prefixes:
    info: "<white>[INFO]: "
    warn: "<yellow>[WARN]: "
    error: "<red>[ERROR]: "

terminal:
  enable_clearing: True