debug: False
timezone: 'America/Chicago'

panel:
  name: 'My Panel'
  url: 'https://example.com'
  api_key: 'CHANGE_ME'

server:
  name: 'My SMP'
  server_id: 'CHANGE_ME'
  domain: 'mc.example.com'
  port: 25565

hungerbridge:
  token: 'CHANGE_ME'
  port: 1913

logger:
  enabled: True
  name: 'Server Watcher'
  log_path: '/home/container/logs/'
  
  prefixes:
    info: '<white>[%hh%:%mm%:%ss%] [INFO]: '
    warn: '<yellow>[%hh%:%mm%:%ss%] [WARN]: '
    error: '<red>[%hh%:%mm%:%ss%] [ERROR]: '
    debug: '<aqua>[%hh%:%mm%:%ss%] [DEBUG]: '

terminal:
  enable_clearing: True
  handle_keyboard_interrupt: True