watch_interval: 300
timezone: 'America/Chicago'

panel:
  name: 'My Panel'
  url: 'https://example.com'
  api_key: 'CHANGE_ME'

origin:
  server_id: 'CHANGE_ME'

server:
  name: 'My SMP'
  server_id: 'CHANGE_ME'
  domain: 'mc.example.com'
  port: 25565
  rcon_port: 25575
  rcon_password: 'password'
  tps_command: 'ticks'

logger:
  enabled: True
  name: 'Server Watcher'
  log_path: '/home/container/logs/'

terminal:
  backspaces: 8
  enable_clearing: True